### ISSUE TITLE
Suggestion to remap ULIDs

### ISSUE THREAD

**Issue by djbusby** [conflabs/wcia-analytes#1]
Since you're using a field called ULIDs and we've been working together and OpenTHC basically introduced ULIDs to the group I'm thinking it makes sense for your ULIDs to match our ULIDs; in the interest of compatibility.  

It might also make sense going forward when adding analytes (aka Lab Metrics) to use the ones we already have defined -- again, for compatibility with existing specifications.

**Comment by bobbyahines** [comment]
Agreed! I will update the docs. Thanks.

**Comment by bobbyahines** [comment]
Adjusted Docs to match.
