### ISSUE TITLE
Add additional solvent and pesticide analytes

### ISSUE THREAD

**Issue by anl360john** [conflabs/wcia-analytes#27]
SOLVENTS
  {
    "ulid": "01FSWJF1C0TGZ76H3GMDQMW39F",
    "scientific_name": "1,4-epoxybutane",
    "common_names": [
      "tetrahydrofuran", 
      "oxolane"
    ],
    "category": "solvent",
    "cas_rn": "109-99-9"
  },

PESTICIDES
  {
    "ulid": "01FSWK1WG0Z79TM9526YECHQ1G",
    "scientific_name": "pyrethrin ii",
    "common_names": [
      "pyrethrin ii"
    ],
    "category": "pesticide",
    "cas_rn": "121-29-9"
  },
  {
    "ulid": "01FSWK5QZM59RC9JDP38ZDBSWM",
    "scientific_name": "3-hydroxy-2,2-dimethyl-3H-1-benzofuran-7-yl",
    "common_names": [
      "3-hydroxycarbofuran"
    ],
    "category": "pesticide",
    "cas_rn": "16655-82-6"
  },
  {
    "ulid": "01FSWKCPMKCD66C59971VKQVZF",
    "scientific_name": "aldoxycarb",
    "common_names": [
      "aldicarb sulfone",
      "aldoxycarb"
    ],
    "category": "pesticide",
    "cas_rn": "1646-88-4"
  },
  {
    "ulid": "01FSWKPNF4GK46JYBPWET4KB8G",
    "scientific_name": "aminocarb",
    "common_names": [
      "aminocarb"
    ],
    "category": "pesticide",
    "cas_rn": "2032-59-9"
  },
  {
    "ulid": "01FSWMY77H81M73RVEVP293E7X",
    "scientific_name": "benalaxyl",
    "common_names": [
      "benalaxyl"
    ],
    "category": "pesticide",
    "cas_rn": "71626-11-4"
  },
  {
    "ulid": "01FSWN23KVYHW9ZDAPNMDWM71B",
    "scientific_name": "butafenacil",
    "common_names": [
      "butafenacil"
    ],
    "category": "pesticide",
    "cas_rn": "134605-64-4"
  },
  {
    "ulid": "01FSWN748MPVADS198GVWDGK9R",
    "scientific_name": "carbetamide",
    "common_names": [
      "carbetamide",
      "legurame"
    ],
    "category": "pesticide",
    "cas_rn": "16118-49-3"
  },
  {
    "ulid": "01FSWNBXMS0V49H2YMSQH1Z7QK",
    "scientific_name": "carboxin",
    "common_names": [
      "carboxin"
    ],
    "category": "pesticide",
    "cas_rn": "5234-68-4"
  },
  {
    "ulid": "01FSWNF61JAP52BARSPRZCW4FC",
    "scientific_name": "carfentrazone-ethyl",
    "common_names": [
      "carfentrazone-ethyl"
    ],
    "category": "pesticide",
    "cas_rn": "128639-02-1"
  },
  {
    "ulid": "01FSWNJ7GAG10GR7GZYJG3QX5W",
    "scientific_name": "chlorotoluron",
    "common_names": [
      "chlorotoluron"
    ],
    "category": "pesticide",
    "cas_rn": "15545-48-9"
  },
  {
    "ulid": "01FSWNNJZXDSFKTXJAJRKVBWND",
    "scientific_name": "chloroxuron",
    "common_names": [
      "chloroxuron"
    ],
    "category": "pesticide",
    "cas_rn": "1982-47-4"
  },
  {
    "ulid": "01FSWNTCQ22Q7RQS9KPEKRYG26",
    "scientific_name": "clothianidin",
    "common_names": [
      "clothianidin"
    ],
    "category": "pesticide",
    "cas_rn": "210880-92-5"
  },
  {
    "ulid": "01FSWNW78050TG10YV202YNCZE",
    "scientific_name": "cyazofamid",
    "common_names": [
      "cyazofamid"
    ],
    "category": "pesticide",
    "cas_rn": "120116-88-3"
  },
  {
    "ulid": "01FSWP02YBJZYYWSFHWHBPZVM0",
    "scientific_name": "cycluron",
    "common_names": [
      "cycluron"
    ],
    "category": "pesticide",
    "cas_rn": "2163-69-1"
  },
  {
    "ulid": "01FSWP2YYGFNGYP8KN3X50XV7W",
    "scientific_name": "diazinon",
    "common_names": [
      "diazinon"
    ],
    "category": "pesticide",
    "cas_rn": "333-41-5"
  },
  {
    "ulid": "01FSWP67YVXTTJAE6J3H129FYY",
    "scientific_name": "dicrotophos",
    "common_names": [
      "dicrotophos"
    ],
    "category": "pesticide",
    "cas_rn": "141-66-2"
  },
  {
    "ulid": "01FSWP8FWJ13QAEVAVM5MP8E6X",
    "scientific_name": "diethofencarb",
    "common_names": [
      "diethofencarb"
    ],
    "category": "pesticide",
    "cas_rn": "87130-20-9"
  },
  {
    "ulid": "01FSWPB86XDMF5J78FXT56YAFR",
    "scientific_name": "dimethomorph",
    "common_names": [
      "dimethomorph"
    ],
    "category": "pesticide",
    "cas_rn": "110488-70-5"
  },
  {
    "ulid": "01FSWPDZWTCCWC4FAS54XN3Z2X",
    "scientific_name": "dimoxystrobin",
    "common_names": [
      "dimoxystrobin"
    ],
    "category": "pesticide",
    "cas_rn": "149961-52-4"
  },
  {
    "ulid": "01FSWPGF263F46JVTM1TF30N6G",
    "scientific_name": "diuron",
    "common_names": [
      "diuron"
    ],
    "category": "pesticide",
    "cas_rn": "330-54-1"
  },
  {
    "ulid": "01FSWPKCA0NXZCVW6Z4SAS2SN6",
    "scientific_name": "epoxiconazole",
    "common_names": [
      "epoxiconazole"
    ],
    "category": "pesticide",
    "cas_rn": "135319-73-2"
  },
  {
    "ulid": "01FSWPNW590YY58VZ3E6F1FZ1W",
    "scientific_name": "ethiofencarb",
    "common_names": [
      "ethiofencarb"
    ],
    "category": "pesticide",
    "cas_rn": "29973-13-5"
  },
  {
    "ulid": "01FSWPVQTRMAF4D36E2YCMQ0QZ",
    "scientific_name": "fenamidone",
    "common_names": [
      "fenamidone"
    ],
    "category": "pesticide",
    "cas_rn": "161326-34-7"
  },
  {
    "ulid": "01FSWPZDK87B8NA4DDGJMBZ5QQ",
    "scientific_name": "fenazaquin",
    "common_names": [
      "fenazaquin"
    ],
    "category": "pesticide",
    "cas_rn": "120928-09-8"
  },
  {
    "ulid": "01FSWQ3M5K7HPFS8WFR8PH4KTX",
    "scientific_name": "fenuron",
    "common_names": [
      "fenuron"
    ],
    "category": "pesticide",
    "cas_rn": "101-42-8"
  },
  {
    "ulid": "01FSWQ7PN17W01ZRDT00RJ21VC",
    "scientific_name": "flonicamid",
    "common_names": [
      "flonicamid"
    ],
    "category": "pesticide",
    "cas_rn": "158062-67-0"
  },
  {
    "ulid": "01FSWQ9XDX44K90A4V8KMACA07",
    "scientific_name": "fluazinam",
    "common_names": [
      "fluazinam"
    ],
    "category": "pesticide",
    "cas_rn": "79622-59-6"
  },
  {
    "ulid": "01FSWQCETXJV3RXGJET0XH3K81",
    "scientific_name": "flufenacet",
    "common_names": [
      "flufenacet"
    ],
    "category": "pesticide",
    "cas_rn": "142459-58-3"
  },
  {
    "ulid": "01FSWQFGQZ2D5G7DEQW0WQ6K06",
    "scientific_name": "fluometuron",
    "common_names": [
      "fluometuron"
    ],
    "category": "pesticide",
    "cas_rn": "2164-17-2"
  },
  {
    "ulid": "01FSWQHY2H58KE6XZTV8TE4QHC",
    "scientific_name": "flutolanil",
    "common_names": [
      "flutolanil"
    ],
    "category": "pesticide",
    "cas_rn": "66332-96-5"
  },
  {
    "ulid": "01FSWQMANVXZ0WWJ9A9SQKH2W5",
    "scientific_name": "fuberidazole",
    "common_names": [
      "fuberidazole"
    ],
    "category": "pesticide",
    "cas_rn": "3878-19-1"
  },
  {
    "ulid": "01FSWQPQ0MWPRP7SKRJD6XCFWE",
    "scientific_name": "furalaxyl",
    "common_names": [
      "furalaxyl"
    ],
    "category": "pesticide",
    "cas_rn": "57646-30-7"
  },
  {
    "ulid": "01FSWQRRWWAED1H5MM7WV9X2H6",
    "scientific_name": "furathiocarb",
    "common_names": [
      "furathiocarb"
    ],
    "category": "pesticide",
    "cas_rn": "65907-30-4"
  },
  {
    "ulid": "01FSWR4TW1P87NRERGE5R8H30J",
    "scientific_name": "indoxacarb",
    "common_names": [
      "indoxacarb"
    ],
    "category": "pesticide",
    "cas_rn": "173584-44-6"
  },
  {
    "ulid": "01FSWR7N7A3FTRW3ZTHD96FX57",
    "scientific_name": "iprovalicarb",
    "common_names": [
      "iprovalicarb"
    ],
    "category": "pesticide",
    "cas_rn": "140923-17-7"
  },
  {
    "ulid": "01FSWRA8NTJ69G4JAKZMR56GYS",
    "scientific_name": "isoprocarb",
    "common_names": [
      "isoprocarb"
    ],
    "category": "pesticide",
    "cas_rn": "2631-40-5"
  },
  {
    "ulid": "01FSWRCRHN50R12GW41HB4JG86",
    "scientific_name": "isoproturon",
    "common_names": [
      "isoproturon"
    ],
    "category": "pesticide",
    "cas_rn": "34123-59-6"
  },
  {
    "ulid": "01FSWRGNHS1K4RGP02PVTT2658",
    "scientific_name": "kresoxym-methyl",
    "common_names": [
      "kresoxym-methyl"
    ],
    "category": "pesticide",
    "cas_rn": "248582-68-5"
  },
  {
    "ulid": "01FSWRKNKW65FYF2WZER3SNZ4M",
    "scientific_name": "mandipropamid",
    "common_names": [
      "mandipropamid"
    ],
    "category": "pesticide",
    "cas_rn": "374726-62-2"
  },
  {
    "ulid": "01FSWRNY2W1MVMATZCBNG2PSHQ",
    "scientific_name": "mefenacet",
    "common_names": [
      "mefenacet"
    ],
    "category": "pesticide",
    "cas_rn": "73250-68-7"
  },
  {
    "ulid": "01FSWRRG2V2NK04ZBKPG1TYB4D",
    "scientific_name": "mepronil",
    "common_names": [
      "mepronil"
    ],
    "category": "pesticide",
    "cas_rn": "55814-41-0"
  },
  {
    "ulid": "01FSWRTQC87E8T3N59DADG41AE",
    "scientific_name": "methabenzthiazuron",
    "common_names": [
      "methabenzthiazuron"
    ],
    "category": "pesticide",
    "cas_rn": "18691-97-9"
  },
  {
    "ulid": "01FSWRWNW2BCCYJB3A70EEBMDN",
    "scientific_name": "methamidophos",
    "common_names": [
      "methamidophos"
    ],
    "category": "pesticide",
    "cas_rn": "10265-92-6"
  },
  {
    "ulid": "01FSWRYWBBTPMGMZAX6072N30J",
    "scientific_name": "methoprotryne",
    "common_names": [
      "methoprotryne"
    ],
    "category": "pesticide",
    "cas_rn": "841-06-5"
  },
  {
    "ulid": "01FSWS1EVG45ATS5XDXJ168CNY",
    "scientific_name": "methoxyfenozide",
    "common_names": [
      "methoxyfenozide"
    ],
    "category": "pesticide",
    "cas_rn": "161050-58-4"
  },
  {
    "ulid": "01FSWS3RVQ9GK8ZBJ41DWCHSWA",
    "scientific_name": "mexacarbate",
    "common_names": [
      "mexacarbate"
    ],
    "category": "pesticide",
    "cas_rn": "315-18-4"
  },
  {
    "ulid": "01FSWS5RG6MA7KGQEP7AFYFDTG",
    "scientific_name": "monocrotophos",
    "common_names": [
      "monocrotophos"
    ],
    "category": "pesticide",
    "cas_rn": "6923-22-4"
  },
  {
    "ulid": "01FSWS8AWVA3D2W6QHPCRASJ9P",
    "scientific_name": "nitenpyram",
    "common_names": [
      "nitenpyram"
    ],
    "category": "pesticide",
    "cas_rn": "150824-47-8"
  },
  {
    "ulid": "01FSWSADHFBZKDN0R7ZXRMT98N",
    "scientific_name": "omethoate",
    "common_names": [
      "omethoate"
    ],
    "category": "pesticide",
    "cas_rn": "1113-02-6"
  },
  {
    "ulid": "01FSWSC7WJH61YNY3CG26ZPS7D",
    "scientific_name": "oxadixyl",
    "common_names": [
      "oxadixyl"
    ],
    "category": "pesticide",
    "cas_rn": "77732-09-3"
  },
  {
    "ulid": "01FSWSENX67X5JYC4R86HBMWZZ",
    "scientific_name": "picoxystrobin",
    "common_names": [
      "picoxystrobin"
    ],
    "category": "pesticide",
    "cas_rn": "117428-22-5"
  },
  {
    "ulid": "01FSWSGZM8WMTK6HNRZ9T9YW7J",
    "scientific_name": "pirimicarb",
    "common_names": [
      "pirimicarb"
    ],
    "category": "pesticide",
    "cas_rn": "23103-98-2"
  },
  {
    "ulid": "01FSWSJRDS0Y2XWGDC6AWBVERF",
    "scientific_name": "prometon",
    "common_names": [
      "prometon"
    ],
    "category": "pesticide",
    "cas_rn": "1610-18-0"
  },
  {
    "ulid": "01FSWSMSMBPAKT4GN12F898ZBD",
    "scientific_name": "propamocarb",
    "common_names": [
      "propamocarb"
    ],
    "category": "pesticide",
    "cas_rn": "24579-73-5"
  },
  {
    "ulid": "01FSWSPED0TBPWFCFTVH5FJ1BD",
    "scientific_name": "propargite",
    "common_names": [
      "propargite"
    ],
    "category": "pesticide",
    "cas_rn": "2312-35-8"
  },
  {
    "ulid": "01FSWSR33X0K554YPWVSRFPPKP",
    "scientific_name": "pymetrozine",
    "common_names": [
      "pymetrozine"
    ],
    "category": "pesticide",
    "cas_rn": "123312-89-0"
  },
  {
    "ulid": "01FSWST34WPFEWYGMCFN5SPF1G",
    "scientific_name": "pyracarbolid",
    "common_names": [
      "pyracarbolid"
    ],
    "category": "pesticide",
    "cas_rn": "24691-76-7"
  },
  {
    "ulid": "01FSWSVY3CJDJNNRJQHNWE183E",
    "scientific_name": "pyraclostrobin",
    "common_names": [
      "pyraclostrobin"
    ],
    "category": "pesticide",
    "cas_rn": "175013-18-0"
  },
  {
    "ulid": "01FSWSZP4BF8YQHHMX0YTCW5QD",
    "scientific_name": "pyriproxyfen",
    "common_names": [
      "pyriproxyfen"
    ],
    "category": "pesticide",
    "cas_rn": "95737-68-1"
  },
  {
    "ulid": "01FSWT1QTEYSSPGJZ6ZYKZ7V5J",
    "scientific_name": "quinoxyfen",
    "common_names": [
      "quinoxyfen"
    ],
    "category": "pesticide",
    "cas_rn": "124495-18-7"
  },
  {
    "ulid": "01FSWT3ECTFYT97NAZFGF8BWG3",
    "scientific_name": "rotenone",
    "common_names": [
      "rotenone"
    ],
    "category": "pesticide",
    "cas_rn": "83-79-4"
  },
  {
    "ulid": "01FSWT5X4J7PNJ4721R95ZA0YD",
    "scientific_name": "tebufenozide",
    "common_names": [
      "tebufenozide"
    ],
    "category": "pesticide",
    "cas_rn": "112410-23-8"
  },
  {
    "ulid": "01FSWT8P1B8B6G49XNY2BDK35F",
    "scientific_name": "tebuthiuron",
    "common_names": [
      "tebuthiuron"
    ],
    "category": "pesticide",
    "cas_rn": "34014-18-1"
  },
  {
    "ulid": "01FSWTB0NXYZA224M3BMZ4F3C2",
    "scientific_name": "thiobencarb",
    "common_names": [
      "thiobencarb"
    ],
    "category": "pesticide",
    "cas_rn": "28249-77-6"
  },
  {
    "ulid": "01FSWTDN1TD9ASS1FRC1W0RZFK",
    "scientific_name": "thiophanate-methyl",
    "common_names": [
      "thiophanate methyl"
    ],
    "category": "pesticide",
    "cas_rn": "23564-05-8"
  },
  {
    "ulid": "01FSWTGHJG11P8X26NDCFD9R05",
    "scientific_name": "tricyclazole",
    "common_names": [
      "tricyclazole"
    ],
    "category": "pesticide",
    "cas_rn": "41814-78-2"
  },
  {
    "ulid": "01FSWTJ8KQCFXR06A70ZF8WAYY",
    "scientific_name": "triflumizole",
    "common_names": [
      "triflumizole"
    ],
    "category": "pesticide",
    "cas_rn": "68694-11-1"
  },
  {
    "ulid": "01FSWTMCSAMY7E2XF7DV86EWZD",
    "scientific_name": "vamidothion",
    "common_names": [
      "vamidothion"
    ],
    "category": "pesticide",
    "cas_rn": "2275-23-2"
  },
  {
    "ulid": "01FSWTPJPSJD0666RCE7MW6ZVD",
    "scientific_name": "zoxamide",
    "common_names": [
      "zoxamide"
    ],
    "category": "pesticide",
    "cas_rn": "156052-68-5"
  },

**Comment by bobbyahines** [comment]
The solvent was definitely missing from both here and OpenTHC lab-metrics. Was able to find local and OpenTHC versions of all the pesticides, though. I think this might have been due to how quick changes were happening this past week.
